// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'intro',
        'index',
      ],
    },
    {
      type: 'category',
      label: 'Humanoid Robotics Curriculum',
      collapsed: false, // Keep this top-level category expanded by default
      items: [
        {
          type: 'category',
          label: 'Module 1: The Robotic Nervous System (ROS 2)',
          items: [
            'ros2-robotics-module/index',
            'ros2-robotics-module/ros2-foundations',
            'ros2-robotics-module/python-ros-control',
            'ros2-robotics-module/humanoid-modeling'
          ],
        },
        {
          type: 'category',
          label: 'Module 2: The Digital Twin (Gazebo & Unity)',
          items: [
            'digital-twin-sim/index',
            'digital-twin-sim/physics-simulation',
            'digital-twin-sim/unity-interaction',
            'digital-twin-sim/simulated-sensors'
          ],
        },
        {
          type: 'category',
          label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
          items: [
            'ai-robot-brain/index',
            'ai-robot-brain/isaac-sim',
            'ai-robot-brain/isaac-ros',
            'ai-robot-brain/nav2-path-planning'
          ],
        },
        {
          type: 'category',
          label: 'Module 4: Vision-Language-Action (VLA)',
          items: [
            'vla-integration/index',
            'vla-integration/voice-to-action',
            'vla-integration/llm-planning',
            'vla-integration/autonomous-humanoid'
          ],
        },
      ],
    },
    // Generate other docs automatically
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
